### ISSUE TITLE
sounds disappeared completely

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#47] opened 2023-10-10 15:33 UTC
https://orthoptera.speciesfile.org/Common/basic/PlaySound.aspx?TaxonNameID=1143093&SoundID=1358

**Comment by typophyllum** [comment] 2023-10-10 18:04
Mentioned three days ago in #45. Hope this serious error will soon be fixed.

**Comment by mjy** [comment] 2023-10-10 18:07
This is because of http:// vs. https://.

**Comment by klausriede** [comment] 2023-10-11 09:35
should be easy to resolve!

**Comment by LocoDelAssembly** [comment] 2023-10-12 16:02
Duplicate of https://github.com/sfg-taxonpages/orthoptera/issues/45 (solved)

**Closed by LocoDelAssembly** 2023-10-12 16:02 UTC

**Comment by klausriede** [comment] 2023-10-13 09:43
yes, great http://orthoptera.archive.speciesfile.org/Common/basic/PlaySound.aspx?TaxonNameID=1105934&SoundID=1233
